/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "globaldom.h"
#include "org_zeromq_gdom_GdomClient.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_gdom_GdomClient__1_1new (JNIEnv *env, jclass c)
{
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) gdom_client_new ();
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_gdom_GdomClient__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    gdom_client_destroy ((gdom_client_t **) &self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_gdom_GdomClient__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    gdom_client_test ((bool) verbose);
}

