/*  =========================================================================
    gdom_client - class description

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of Global Domination. Resistance is useless.     
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef GDOM_CLIENT_H_INCLUDED
#define GDOM_CLIENT_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/gdom_client.api" to make changes.
//  @interface
//  This is a draft class, and may change without notice. It is disabled in
//  stable builds by default. If you use this in applications, please ask
//  for it to be pushed to stable state. Use --enable-drafts to enable.
#ifdef GDOM_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a new Global Domination client
GDOM_EXPORT gdom_client_t *
    gdom_client_new (void);

//  *** Draft method, for development use, may change without warning ***
//  Destroy a Global Domination client
GDOM_EXPORT void
    gdom_client_destroy (gdom_client_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
GDOM_EXPORT void
    gdom_client_test (bool verbose);

#endif // GDOM_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
